import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

type Project = {
    name: string,
    slug: string,
    color: string
};

const PROJECTS = [
    {
        name: 'Messages',
        slug: 'messages',
        color: 'green'
    },
    {
        name: 'Algorithms',
        slug: 'algorithms',
        color: 'purple'
    }
] satisfies Project[];

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Example Projects by Balázs Burján</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='flex min-h-screen flex-col items-center justify-center bg-theme-dark-bg'>
                <div className='container flex flex-col items-center justify-center gap-12 px-4 py-16 '>
                    <h1 className='text-5xl font-bold text-white'>
                        Example Projects
                        <div>
                            <span>
                                by&nbsp;
                            </span>
                            <span className='text-theme-red'>
                                Balázs Burján
                            </span>
                        </div>
                    </h1>
                    <div className='grid grid-flow-col auto-cols-fr gap-4'>
                        {PROJECTS.map((project) => (
                            <Link key={project.slug} href={`/project/${project.slug}`}>
                                <div
                                    style={{ background: project.color }}
                                    className={`
                                        aspect-square flex justify-center items-center p-4 px-12
                                        rounded-lg border border-[rgb(255,255,255,0.15)]
                                    `}
                                >
                                    <h2 className='text-3xl font-medium text-white'>
                                        {project.name}
                                    </h2>
                                </div>
                            </Link>
                        ))}
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;
